/*
 * readmesh.cpp
 *
 *  Created on: Apr. 7th, 2021
 *      Author: Dr. R. Poller
 *
 *  Synopsis
 *  	Reads mesh data from the standard input
 *
 *  	The reading is done by modules generated by
 *  	bison (parser) and flex (lexical analyzer)
 *
 */

#include <iostream>

#include "Point.h"
#include "Polygon.h"

#include "meshparser.tab.hpp"

typedef pair<NodeSet, ElemSet> FEMesh;

extern void WriteStepTitle(const string&);

FEMesh *p_mesh;

void ReadFEMesh(FEMesh& mesh)
{
	p_mesh = &mesh;
	yy::parser meshreader;

	WriteStepTitle("Reading mesh data");
	meshreader.parse();
}

