/*
 * readmesh.cpp
 *
 *  Created on: Apr. 7th, 2021
 *      Author: Dr. Rudolf Poller
 *
 *  Synopsis
 *  	Reads mesh data from the standard input
 *
 *  	The reading is done by modules generated by
 *  	bison (parser) and flex (lexical analyzer)
 *
 */

using namespace std;

#include "../mesh/Point.h"
#include "../mesh/Polygon.h"

#include "meshparser.tab.hpp"
#include "ansparser.tab.hpp"

extern string problem_title;
extern void writeStepTitle(const string&);

const yy::parser::debug_level_type      ParserDebug = 0;
const ans::parser::debug_level_type ans_ParserDebug = 0;

typedef std::pair<NodeSet, ElemSet> FEMesh;
FEMesh *p_mesh;

void writeStatistics(void);

void readFEMesh(input_grammar format, FEMesh& mesh)
{
	p_mesh = &mesh;
	writeStepTitle("Reading mesh data");
	switch (format) {
	case ansys:
		{
			ans::parser meshreader;
			meshreader.set_debug_level(ans_ParserDebug);
			meshreader.parse();
			break;
		}
	case meshplot:
	default:
		{
			yy::parser meshreader;
			meshreader.set_debug_level(ParserDebug);
			meshreader.parse();
			break;
		}
	}
	writeStatistics();
}

#define FIELDWIDTH  4

void writeStatistics(void)
{
	if (problem_title.size())
		cout << problem_title << endl;
	else
	    cout << " --- No title specified ---" << endl;
	cout << "\tnumber of nodes:    " << setw(FIELDWIDTH)
	        << p_mesh->first.size() << endl;
	cout << "\tnumber of elements: " << setw(FIELDWIDTH)
	        << p_mesh->second.size() << endl;
}

